source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
#
# # Specify your gem's dependencies in daily_deal.gemspec
# daily_deal.gemspec
gem 'pry'
gem 'nokogiri'
